# Specify general parameters
channels: [DNA,AGP,ER,Mito,RNA]         # This is also used for the load data
bucket_name: cellpainting-gallery       # So is this

# Specify the class to use for preprocessing and the parameters
download_class:
    _target_: jump_download.images.final_image_class.Robust8BitCropPNGScenario
    percentile: 1.0
    min_resolution_x: 768
    min_resolution_y: 768
    channels: ${processing.channels}
    bucket_name: ${processing.bucket_name}
